### ISSUE TITLE
Ugly kludge?

### ISSUE THREAD

**Issue by felias-fogg** [rouming/AVR-GDBServer#2]
In line 812 following (gdb.c), you write:

> XXX: this is ugly kludge, but what can I do?
					AVR puts return address on stack with garbage in high
					bits (they say you should mask out them, see Stack Pointer
					section at every AVR datasheet), but how can I understand
					that this word is ret address? To have valid backtrace in
					gdb, I'am required to mask every word, which address belongs
					to stack.

The "ugly kludge" leads to displaying wrong values of local variables by gdb! I tried to verify the problem you mentioned, but did not find anything in the AVR data sheets. Can you point out the document that describes this phenomenon?

**Comment by rouming** [comment]
Ha! That was 9 years ago (according to the commits history :) Frankly speaking since then I never used AVR anymore. I would be happy to apply your patch if you can help and find out is this kludge useful or not.

**Comment by felias-fogg** [comment]
I stumbled over it in another implementation of a gdb-stub for AVRs: https://github.com/jdolinay/avr_debug 
I corrected it in this code and it worked. But I am curious about whether there were actually documents that state the problem of random insertions of garbage in the high (unused) bits, and if so, which MCU had this problem.  

In any case, I sent you a pull request.

Best,
Bernhard

**Comment by rouming** [comment]
I applied your request, thanks. I remember I used atmega back in a days, but unfortunately that is all what I remember :) For the testing purposes I used some sorting algorithm taken from the Linux kernel, and seems the testing file should be in the repo, so basically that is the only test I tried.

The biggest problem with the software gdbserver was the amount of memory it occupies on AVR (can imagine there is something fat on the market this days) . So I did not find it practical at the end and never used.

**Comment by ccrause** [comment]
Just out of interest, the following discussion mentioned the high bits return address issue: https://www.avrfreaks.net/forum/address-stack-has-always-bit

So it appears as if at least the atmega16 is affected (but not the A version), maybe some other older controllers too. For the atmega16 I would think the downstream consumer needs to apply a return address mask when it is expecting a return address off the stack.

For what it is worth, I support removing this hack.

**Comment by rouming** [comment]
Would be great. I'm open to apply patches. What if to put the kludge under ifdef?

--
Roman

**Comment by felias-fogg** [comment]
> Just out of interest, the following discussion mentioned the high bits return address issue: https://www.avrfreaks.net/forum/address-stack-has-always-bit
> 
> So it appears as if at least the atmega16 is affected (but not the A version), maybe some other older controllers too. For the atmega16 I would think the downstream consumer needs to apply a return address mask when it is expecting a return address off the stack.
> 
> For what it is worth, I support removing this hack.

Thanks for this hint!

**Comment by ccrause** [comment]
> Would be great. I'm open to apply patches. What if to put the kludge under ifdef?
> 
> --
> Roman
I meant to say that this hack should not sit in AVR-Gdbserver, but in the program that connects to it, probably gdb. So gdb should know when it is interpreting return addresses and then apply a controller specific mask as needed. 

So the patch that disabled it (pull request #3) is good in my opinion.

**Comment by rouming** [comment]
> > Would be great. I'm open to apply patches. What if to put the kludge under ifdef?
> > --
> > Roman
> > I meant to say that this hack should not sit in AVR-Gdbserver, but in the program that connects to it, probably gdb. So gdb should know when it is interpreting return addresses and then apply a controller specific mask as needed.
> 
> So the patch that disabled it (pull request #3) is good in my opinion.

 All clear. Thanks.
